/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calc;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class DetallePromedio extends javax.swing.JFrame
{

    private int rowH, rowW, fontS;

    /**
     * Creates new form DetallePromedio
     */
    public DetallePromedio(Object o[][])
    {
        initComponents();
        init2(o);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Fecha Inicio", "Fecha fin", "Sueldo", "Semanas"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("zoom +");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("zoom -");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        rowH += 20;
        rowW += 40;
        fontS += 2;
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(rowW);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(rowW);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(rowW);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(rowW);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(rowW);
            jTable1.setRowHeight(rowH);
            jTable1.getTableHeader().setSize(100, 11000);
            jTable1.setFont(new java.awt.Font("Segoe UI", 0, fontS));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        rowH -= 20;
        rowW -= 20;
        fontS -= 2;
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            if (rowW > 1)
            {
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(rowW);
                jTable1.getColumnModel().getColumn(1).setPreferredWidth(rowW);
                jTable1.getColumnModel().getColumn(2).setPreferredWidth(rowW);
                jTable1.getColumnModel().getColumn(3).setPreferredWidth(rowW);
            } else
            {
                rowW = 1;
            }
            if (rowH > 1)
            {
                jTable1.setRowHeight(rowH);
            } else
            {
                rowH = 1;
            }
            if (fontS >= 12)
            {
                jTable1.setFont(new java.awt.Font("Segoe UI", 0, fontS));
            } else
            {
                fontS = 10;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DetallePromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DetallePromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DetallePromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DetallePromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new DetallePromedio(null).setVisible(true);
            }
        });
    }

    public void llenarTabla(Object o[][])
    {
        DefaultTableModel dfm = new DefaultTableModel();
        jTable1.setModel(dfm);
        dfm.addColumn("Fecha inicio");
        dfm.addColumn("Fecha fin");
        dfm.addColumn("Sueldo");
        dfm.addColumn("Semanas");
        for (int i = 0; i < o.length; i++)
        {
            dfm.addRow(o[i]);
        }
    }

    private void init2(Object o[][])
    {
        this.rowH = jTable1.getRowHeight();
        this.rowW = jTable1.getColumnModel().getColumn(0).getPreferredWidth();
        this.fontS = jTable1.getFont().getSize();
        llenarTabla(o);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
